version: "3.8"
services:
  visdom:
    image: "hypnosapos/visdom:e0a912d"
    ports:
        - "8097:8097"
  texsyn:
    build: .
    volumes:
      - ./datasets:/app/datasets
    depends_on: [ visdom ]
